// Code generated by hertz generator.

package main

import (
	handler "github.com/Cs1799205202/API-Gateway/biz/handler"
	"github.com/Cs1799205202/API-Gateway/biz/handler/gateway"
	"github.com/Cs1799205202/API-Gateway/biz/handler/idl_management"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	r.GET("/agw/", gateway.Greeting)

	r.GET("/idl/list", idl_management.ListService)

	r.POST("/idl/update/:servicename", idl_management.UpdateService)
	r.DELETE("/idl/delete/:servicename", idl_management.DeleteService)

	// your code ...
}

func Register(r *server.Hertz) {
	customizedRegister(r)
}