// Code generated by Kitex v0.6.1. DO NOT EDIT.
package upperservice

import (
	server "github.com/cloudwego/kitex/server"
	upper "upper/kitex_gen/upper"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler upper.UpperService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
