// Code generated by Kitex v0.6.1. DO NOT EDIT.

package lowerservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	lower "lower/kitex_gen/lower"
)

func serviceInfo() *kitex.ServiceInfo {
	return lowerServiceServiceInfo
}

var lowerServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "LowerService"
	handlerType := (*lower.LowerService)(nil)
	methods := map[string]kitex.MethodInfo{
		"tolower": kitex.NewMethodInfo(tolowerHandler, newLowerServiceTolowerArgs, newLowerServiceTolowerResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "lower",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.6.1",
		Extra:           extra,
	}
	return svcInfo
}

func tolowerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*lower.LowerServiceTolowerArgs)
	realResult := result.(*lower.LowerServiceTolowerResult)
	success, err := handler.(lower.LowerService).Tolower(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLowerServiceTolowerArgs() interface{} {
	return lower.NewLowerServiceTolowerArgs()
}

func newLowerServiceTolowerResult() interface{} {
	return lower.NewLowerServiceTolowerResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Tolower(ctx context.Context, req *lower.NormalRequest) (r *lower.LowerResponse, err error) {
	var _args lower.LowerServiceTolowerArgs
	_args.Req = req
	var _result lower.LowerServiceTolowerResult
	if err = p.c.Call(ctx, "tolower", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
